language: node_js
node_js:
  - '10'
  - '12'
  - '14'

cache: npm

deploy:
  provider: npm
  email: hypnos3@online.de
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
    - hypnos3@online.de
    on_success: change
    on_failure: always
